# You're playlist file that you exported from iTunes.
playlist: /tmp/playlist.xml

# The codecs that your mp3 player supports. The first is what your unsupported
# files will be encoded to.
supported_codecs:
  - mp3
  - aac

# Where to save your files.
#   %n    track number
#   %a    artist
#   %A    album
#   %t    song title
#   %T    song title with substituted charactors
#   %y    year
library_path: '/tmp/%a/[%y] %A/%n-%T.%e'
